/// Currency data model for world currencies
class CurrencyData {
  final String code;
  final String symbol;
  final String name;
  final String country;
  final String flag;

  const CurrencyData({
    required this.code,
    required this.symbol,
    required this.name,
    required this.country,
    required this.flag,
  });
}

/// Default currency (Indian Rupee)
CurrencyData get defaultCurrency => worldCurrencies.firstWhere(
      (c) => c.code == 'INR',
      orElse: () => worldCurrencies.first,
    );

/// List of all world currencies sorted by country name
const List<CurrencyData> worldCurrencies = [
  CurrencyData(code: 'AFN', symbol: '؋', name: 'Afghan Afghani', country: 'Afghanistan', flag: '🇦🇫'),
  CurrencyData(code: 'ALL', symbol: 'L', name: 'Albanian Lek', country: 'Albania', flag: '🇦🇱'),
  CurrencyData(code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar', country: 'Algeria', flag: '🇩🇿'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Andorra', flag: '🇦🇩'),
  CurrencyData(code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', country: 'Angola', flag: '🇦🇴'),
  CurrencyData(code: 'XCD', symbol: '\$', name: 'East Caribbean Dollar', country: 'Antigua and Barbuda', flag: '🇦🇬'),
  CurrencyData(code: 'ARS', symbol: '\$', name: 'Argentine Peso', country: 'Argentina', flag: '🇦🇷'),
  CurrencyData(code: 'AMD', symbol: '֏', name: 'Armenian Dram', country: 'Armenia', flag: '🇦🇲'),
  CurrencyData(code: 'AUD', symbol: '\$', name: 'Australian Dollar', country: 'Australia', flag: '🇦🇺'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Austria', flag: '🇦🇹'),
  CurrencyData(code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', country: 'Azerbaijan', flag: '🇦🇿'),
  CurrencyData(code: 'BSD', symbol: '\$', name: 'Bahamian Dollar', country: 'Bahamas', flag: '🇧🇸'),
  CurrencyData(code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar', country: 'Bahrain', flag: '🇧🇭'),
  CurrencyData(code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', country: 'Bangladesh', flag: '🇧🇩'),
  CurrencyData(code: 'BBD', symbol: '\$', name: 'Barbadian Dollar', country: 'Barbados', flag: '🇧🇧'),
  CurrencyData(code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', country: 'Belarus', flag: '🇧🇾'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Belgium', flag: '🇧🇪'),
  CurrencyData(code: 'BZD', symbol: '\$', name: 'Belize Dollar', country: 'Belize', flag: '🇧🇿'),
  CurrencyData(code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', country: 'Benin', flag: '🇧🇯'),
  CurrencyData(code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum', country: 'Bhutan', flag: '🇧🇹'),
  CurrencyData(code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano', country: 'Bolivia', flag: '🇧🇴'),
  CurrencyData(code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Mark', country: 'Bosnia and Herzegovina', flag: '🇧🇦'),
  CurrencyData(code: 'BWP', symbol: 'P', name: 'Botswanan Pula', country: 'Botswana', flag: '🇧🇼'),
  CurrencyData(code: 'BRL', symbol: 'R\$', name: 'Brazilian Real', country: 'Brazil', flag: '🇧🇷'),
  CurrencyData(code: 'BND', symbol: '\$', name: 'Brunei Dollar', country: 'Brunei', flag: '🇧🇳'),
  CurrencyData(code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', country: 'Bulgaria', flag: '🇧🇬'),
  CurrencyData(code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', country: 'Burkina Faso', flag: '🇧🇫'),
  CurrencyData(code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', country: 'Burundi', flag: '🇧🇮'),
  CurrencyData(code: 'KHR', symbol: '៛', name: 'Cambodian Riel', country: 'Cambodia', flag: '🇰🇭'),
  CurrencyData(code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', country: 'Cameroon', flag: '🇨🇲'),
  CurrencyData(code: 'CAD', symbol: '\$', name: 'Canadian Dollar', country: 'Canada', flag: '🇨🇦'),
  CurrencyData(code: 'CVE', symbol: '\$', name: 'Cape Verdean Escudo', country: 'Cape Verde', flag: '🇨🇻'),
  CurrencyData(code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', country: 'Central African Republic', flag: '🇨🇫'),
  CurrencyData(code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', country: 'Chad', flag: '🇹🇩'),
  CurrencyData(code: 'CLP', symbol: '\$', name: 'Chilean Peso', country: 'Chile', flag: '🇨🇱'),
  CurrencyData(code: 'CNY', symbol: '¥', name: 'Chinese Yuan', country: 'China', flag: '🇨🇳'),
  CurrencyData(code: 'COP', symbol: '\$', name: 'Colombian Peso', country: 'Colombia', flag: '🇨🇴'),
  CurrencyData(code: 'KMF', symbol: 'CF', name: 'Comorian Franc', country: 'Comoros', flag: '🇰🇲'),
  CurrencyData(code: 'CDF', symbol: 'FC', name: 'Congolese Franc', country: 'Congo (DRC)', flag: '🇨🇩'),
  CurrencyData(code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', country: 'Congo (Republic)', flag: '🇨🇬'),
  CurrencyData(code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', country: 'Costa Rica', flag: '🇨🇷'),
  CurrencyData(code: 'HRK', symbol: 'kn', name: 'Croatian Kuna', country: 'Croatia', flag: '🇭🇷'),
  CurrencyData(code: 'CUP', symbol: '\$', name: 'Cuban Peso', country: 'Cuba', flag: '🇨🇺'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Cyprus', flag: '🇨🇾'),
  CurrencyData(code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', country: 'Czech Republic', flag: '🇨🇿'),
  CurrencyData(code: 'DKK', symbol: 'kr', name: 'Danish Krone', country: 'Denmark', flag: '🇩🇰'),
  CurrencyData(code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', country: 'Djibouti', flag: '🇩🇯'),
  CurrencyData(code: 'XCD', symbol: '\$', name: 'East Caribbean Dollar', country: 'Dominica', flag: '🇩🇲'),
  CurrencyData(code: 'DOP', symbol: 'RD\$', name: 'Dominican Peso', country: 'Dominican Republic', flag: '🇩🇴'),
  CurrencyData(code: 'USD', symbol: '\$', name: 'US Dollar', country: 'Ecuador', flag: '🇪🇨'),
  CurrencyData(code: 'EGP', symbol: '£', name: 'Egyptian Pound', country: 'Egypt', flag: '🇪🇬'),
  CurrencyData(code: 'USD', symbol: '\$', name: 'US Dollar', country: 'El Salvador', flag: '🇸🇻'),
  CurrencyData(code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', country: 'Equatorial Guinea', flag: '🇬🇶'),
  CurrencyData(code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa', country: 'Eritrea', flag: '🇪🇷'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Estonia', flag: '🇪🇪'),
  CurrencyData(code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni', country: 'Eswatini', flag: '🇸🇿'),
  CurrencyData(code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', country: 'Ethiopia', flag: '🇪🇹'),
  CurrencyData(code: 'FJD', symbol: '\$', name: 'Fijian Dollar', country: 'Fiji', flag: '🇫🇯'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Finland', flag: '🇫🇮'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'France', flag: '🇫🇷'),
  CurrencyData(code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', country: 'Gabon', flag: '🇬🇦'),
  CurrencyData(code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', country: 'Gambia', flag: '🇬🇲'),
  CurrencyData(code: 'GEL', symbol: '₾', name: 'Georgian Lari', country: 'Georgia', flag: '🇬🇪'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Germany', flag: '🇩🇪'),
  CurrencyData(code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi', country: 'Ghana', flag: '🇬🇭'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Greece', flag: '🇬🇷'),
  CurrencyData(code: 'XCD', symbol: '\$', name: 'East Caribbean Dollar', country: 'Grenada', flag: '🇬🇩'),
  CurrencyData(code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', country: 'Guatemala', flag: '🇬🇹'),
  CurrencyData(code: 'GNF', symbol: 'FG', name: 'Guinean Franc', country: 'Guinea', flag: '🇬🇳'),
  CurrencyData(code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', country: 'Guinea-Bissau', flag: '🇬🇼'),
  CurrencyData(code: 'GYD', symbol: '\$', name: 'Guyanese Dollar', country: 'Guyana', flag: '🇬🇾'),
  CurrencyData(code: 'HTG', symbol: 'G', name: 'Haitian Gourde', country: 'Haiti', flag: '🇭🇹'),
  CurrencyData(code: 'HNL', symbol: 'L', name: 'Honduran Lempira', country: 'Honduras', flag: '🇭🇳'),
  CurrencyData(code: 'HKD', symbol: '\$', name: 'Hong Kong Dollar', country: 'Hong Kong', flag: '🇭🇰'),
  CurrencyData(code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', country: 'Hungary', flag: '🇭🇺'),
  CurrencyData(code: 'ISK', symbol: 'kr', name: 'Icelandic Króna', country: 'Iceland', flag: '🇮🇸'),
  CurrencyData(code: 'INR', symbol: '₹', name: 'Indian Rupee', country: 'India', flag: '🇮🇳'),
  CurrencyData(code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', country: 'Indonesia', flag: '🇮🇩'),
  CurrencyData(code: 'IRR', symbol: '﷼', name: 'Iranian Rial', country: 'Iran', flag: '🇮🇷'),
  CurrencyData(code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar', country: 'Iraq', flag: '🇮🇶'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Ireland', flag: '🇮🇪'),
  CurrencyData(code: 'ILS', symbol: '₪', name: 'Israeli New Shekel', country: 'Israel', flag: '🇮🇱'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Italy', flag: '🇮🇹'),
  CurrencyData(code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', country: 'Ivory Coast', flag: '🇨🇮'),
  CurrencyData(code: 'JMD', symbol: '\$', name: 'Jamaican Dollar', country: 'Jamaica', flag: '🇯🇲'),
  CurrencyData(code: 'JPY', symbol: '¥', name: 'Japanese Yen', country: 'Japan', flag: '🇯🇵'),
  CurrencyData(code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar', country: 'Jordan', flag: '🇯🇴'),
  CurrencyData(code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', country: 'Kazakhstan', flag: '🇰🇿'),
  CurrencyData(code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', country: 'Kenya', flag: '🇰🇪'),
  CurrencyData(code: 'AUD', symbol: '\$', name: 'Australian Dollar', country: 'Kiribati', flag: '🇰🇮'),
  CurrencyData(code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', country: 'Kuwait', flag: '🇰🇼'),
  CurrencyData(code: 'KGS', symbol: 'лв', name: 'Kyrgystani Som', country: 'Kyrgyzstan', flag: '🇰🇬'),
  CurrencyData(code: 'LAK', symbol: '₭', name: 'Laotian Kip', country: 'Laos', flag: '🇱🇦'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Latvia', flag: '🇱🇻'),
  CurrencyData(code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound', country: 'Lebanon', flag: '🇱🇧'),
  CurrencyData(code: 'LSL', symbol: 'M', name: 'Lesotho Loti', country: 'Lesotho', flag: '🇱🇸'),
  CurrencyData(code: 'LRD', symbol: '\$', name: 'Liberian Dollar', country: 'Liberia', flag: '🇱🇷'),
  CurrencyData(code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar', country: 'Libya', flag: '🇱🇾'),
  CurrencyData(code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', country: 'Liechtenstein', flag: '🇱🇮'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Lithuania', flag: '🇱🇹'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Luxembourg', flag: '🇱🇺'),
  CurrencyData(code: 'MOP', symbol: 'MOP\$', name: 'Macanese Pataca', country: 'Macau', flag: '🇲🇴'),
  CurrencyData(code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', country: 'Madagascar', flag: '🇲🇬'),
  CurrencyData(code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', country: 'Malawi', flag: '🇲🇼'),
  CurrencyData(code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', country: 'Malaysia', flag: '🇲🇾'),
  CurrencyData(code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa', country: 'Maldives', flag: '🇲🇻'),
  CurrencyData(code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', country: 'Mali', flag: '🇲🇱'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Malta', flag: '🇲🇹'),
  CurrencyData(code: 'USD', symbol: '\$', name: 'US Dollar', country: 'Marshall Islands', flag: '🇲🇭'),
  CurrencyData(code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya', country: 'Mauritania', flag: '🇲🇷'),
  CurrencyData(code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', country: 'Mauritius', flag: '🇲🇺'),
  CurrencyData(code: 'MXN', symbol: '\$', name: 'Mexican Peso', country: 'Mexico', flag: '🇲🇽'),
  CurrencyData(code: 'USD', symbol: '\$', name: 'US Dollar', country: 'Micronesia', flag: '🇫🇲'),
  CurrencyData(code: 'MDL', symbol: 'L', name: 'Moldovan Leu', country: 'Moldova', flag: '🇲🇩'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Monaco', flag: '🇲🇨'),
  CurrencyData(code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik', country: 'Mongolia', flag: '🇲🇳'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Montenegro', flag: '🇲🇪'),
  CurrencyData(code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham', country: 'Morocco', flag: '🇲🇦'),
  CurrencyData(code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', country: 'Mozambique', flag: '🇲🇿'),
  CurrencyData(code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', country: 'Myanmar', flag: '🇲🇲'),
  CurrencyData(code: 'NAD', symbol: '\$', name: 'Namibian Dollar', country: 'Namibia', flag: '🇳🇦'),
  CurrencyData(code: 'AUD', symbol: '\$', name: 'Australian Dollar', country: 'Nauru', flag: '🇳🇷'),
  CurrencyData(code: 'NPR', symbol: '₨', name: 'Nepalese Rupee', country: 'Nepal', flag: '🇳🇵'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Netherlands', flag: '🇳🇱'),
  CurrencyData(code: 'NZD', symbol: '\$', name: 'New Zealand Dollar', country: 'New Zealand', flag: '🇳🇿'),
  CurrencyData(code: 'NIO', symbol: 'C\$', name: 'Nicaraguan Córdoba', country: 'Nicaragua', flag: '🇳🇮'),
  CurrencyData(code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', country: 'Niger', flag: '🇳🇪'),
  CurrencyData(code: 'NGN', symbol: '₦', name: 'Nigerian Naira', country: 'Nigeria', flag: '🇳🇬'),
  CurrencyData(code: 'KPW', symbol: '₩', name: 'North Korean Won', country: 'North Korea', flag: '🇰🇵'),
  CurrencyData(code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', country: 'North Macedonia', flag: '🇲🇰'),
  CurrencyData(code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', country: 'Norway', flag: '🇳🇴'),
  CurrencyData(code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial', country: 'Oman', flag: '🇴🇲'),
  CurrencyData(code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', country: 'Pakistan', flag: '🇵🇰'),
  CurrencyData(code: 'USD', symbol: '\$', name: 'US Dollar', country: 'Palau', flag: '🇵🇼'),
  CurrencyData(code: 'ILS', symbol: '₪', name: 'Israeli New Shekel', country: 'Palestine', flag: '🇵🇸'),
  CurrencyData(code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', country: 'Panama', flag: '🇵🇦'),
  CurrencyData(code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', country: 'Papua New Guinea', flag: '🇵🇬'),
  CurrencyData(code: 'PYG', symbol: '₲', name: 'Paraguayan Guarani', country: 'Paraguay', flag: '🇵🇾'),
  CurrencyData(code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', country: 'Peru', flag: '🇵🇪'),
  CurrencyData(code: 'PHP', symbol: '₱', name: 'Philippine Peso', country: 'Philippines', flag: '🇵🇭'),
  CurrencyData(code: 'PLN', symbol: 'zł', name: 'Polish Zloty', country: 'Poland', flag: '🇵🇱'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Portugal', flag: '🇵🇹'),
  CurrencyData(code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal', country: 'Qatar', flag: '🇶🇦'),
  CurrencyData(code: 'RON', symbol: 'lei', name: 'Romanian Leu', country: 'Romania', flag: '🇷🇴'),
  CurrencyData(code: 'RUB', symbol: '₽', name: 'Russian Ruble', country: 'Russia', flag: '🇷🇺'),
  CurrencyData(code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc', country: 'Rwanda', flag: '🇷🇼'),
  CurrencyData(code: 'XCD', symbol: '\$', name: 'East Caribbean Dollar', country: 'Saint Kitts and Nevis', flag: '🇰🇳'),
  CurrencyData(code: 'XCD', symbol: '\$', name: 'East Caribbean Dollar', country: 'Saint Lucia', flag: '🇱🇨'),
  CurrencyData(code: 'XCD', symbol: '\$', name: 'East Caribbean Dollar', country: 'Saint Vincent', flag: '🇻🇨'),
  CurrencyData(code: 'WST', symbol: 'WS\$', name: 'Samoan Tala', country: 'Samoa', flag: '🇼🇸'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'San Marino', flag: '🇸🇲'),
  CurrencyData(code: 'STN', symbol: 'Db', name: 'São Tomé Dobra', country: 'São Tomé and Príncipe', flag: '🇸🇹'),
  CurrencyData(code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal', country: 'Saudi Arabia', flag: '🇸🇦'),
  CurrencyData(code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', country: 'Senegal', flag: '🇸🇳'),
  CurrencyData(code: 'RSD', symbol: 'дин.', name: 'Serbian Dinar', country: 'Serbia', flag: '🇷🇸'),
  CurrencyData(code: 'SCR', symbol: '₨', name: 'Seychellois Rupee', country: 'Seychelles', flag: '🇸🇨'),
  CurrencyData(code: 'SLE', symbol: 'Le', name: 'Sierra Leonean Leone', country: 'Sierra Leone', flag: '🇸🇱'),
  CurrencyData(code: 'SGD', symbol: '\$', name: 'Singapore Dollar', country: 'Singapore', flag: '🇸🇬'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Slovakia', flag: '🇸🇰'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Slovenia', flag: '🇸🇮'),
  CurrencyData(code: 'SBD', symbol: '\$', name: 'Solomon Islands Dollar', country: 'Solomon Islands', flag: '🇸🇧'),
  CurrencyData(code: 'SOS', symbol: 'S', name: 'Somali Shilling', country: 'Somalia', flag: '🇸🇴'),
  CurrencyData(code: 'ZAR', symbol: 'R', name: 'South African Rand', country: 'South Africa', flag: '🇿🇦'),
  CurrencyData(code: 'KRW', symbol: '₩', name: 'South Korean Won', country: 'South Korea', flag: '🇰🇷'),
  CurrencyData(code: 'SSP', symbol: '£', name: 'South Sudanese Pound', country: 'South Sudan', flag: '🇸🇸'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Spain', flag: '🇪🇸'),
  CurrencyData(code: 'LKR', symbol: '₨', name: 'Sri Lankan Rupee', country: 'Sri Lanka', flag: '🇱🇰'),
  CurrencyData(code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound', country: 'Sudan', flag: '🇸🇩'),
  CurrencyData(code: 'SRD', symbol: '\$', name: 'Surinamese Dollar', country: 'Suriname', flag: '🇸🇷'),
  CurrencyData(code: 'SEK', symbol: 'kr', name: 'Swedish Krona', country: 'Sweden', flag: '🇸🇪'),
  CurrencyData(code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', country: 'Switzerland', flag: '🇨🇭'),
  CurrencyData(code: 'SYP', symbol: '£', name: 'Syrian Pound', country: 'Syria', flag: '🇸🇾'),
  CurrencyData(code: 'TWD', symbol: 'NT\$', name: 'New Taiwan Dollar', country: 'Taiwan', flag: '🇹🇼'),
  CurrencyData(code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni', country: 'Tajikistan', flag: '🇹🇯'),
  CurrencyData(code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', country: 'Tanzania', flag: '🇹🇿'),
  CurrencyData(code: 'THB', symbol: '฿', name: 'Thai Baht', country: 'Thailand', flag: '🇹🇭'),
  CurrencyData(code: 'USD', symbol: '\$', name: 'US Dollar', country: 'Timor-Leste', flag: '🇹🇱'),
  CurrencyData(code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', country: 'Togo', flag: '🇹🇬'),
  CurrencyData(code: 'TOP', symbol: 'T\$', name: 'Tongan Paʻanga', country: 'Tonga', flag: '🇹🇴'),
  CurrencyData(code: 'TTD', symbol: 'TT\$', name: 'Trinidad & Tobago Dollar', country: 'Trinidad and Tobago', flag: '🇹🇹'),
  CurrencyData(code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar', country: 'Tunisia', flag: '🇹🇳'),
  CurrencyData(code: 'TRY', symbol: '₺', name: 'Turkish Lira', country: 'Turkey', flag: '🇹🇷'),
  CurrencyData(code: 'TMT', symbol: 'T', name: 'Turkmenistani Manat', country: 'Turkmenistan', flag: '🇹🇲'),
  CurrencyData(code: 'AUD', symbol: '\$', name: 'Australian Dollar', country: 'Tuvalu', flag: '🇹🇻'),
  CurrencyData(code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', country: 'Uganda', flag: '🇺🇬'),
  CurrencyData(code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', country: 'Ukraine', flag: '🇺🇦'),
  CurrencyData(code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', country: 'United Arab Emirates', flag: '🇦🇪'),
  CurrencyData(code: 'GBP', symbol: '£', name: 'British Pound', country: 'United Kingdom', flag: '🇬🇧'),
  CurrencyData(code: 'USD', symbol: '\$', name: 'US Dollar', country: 'United States', flag: '🇺🇸'),
  CurrencyData(code: 'UYU', symbol: '\$U', name: 'Uruguayan Peso', country: 'Uruguay', flag: '🇺🇾'),
  CurrencyData(code: 'UZS', symbol: 'лв', name: 'Uzbekistani Som', country: 'Uzbekistan', flag: '🇺🇿'),
  CurrencyData(code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', country: 'Vanuatu', flag: '🇻🇺'),
  CurrencyData(code: 'EUR', symbol: '€', name: 'Euro', country: 'Vatican City', flag: '🇻🇦'),
  CurrencyData(code: 'VES', symbol: 'Bs.S', name: 'Venezuelan Bolívar', country: 'Venezuela', flag: '🇻🇪'),
  CurrencyData(code: 'VND', symbol: '₫', name: 'Vietnamese Dong', country: 'Vietnam', flag: '🇻🇳'),
  CurrencyData(code: 'YER', symbol: '﷼', name: 'Yemeni Rial', country: 'Yemen', flag: '🇾🇪'),
  CurrencyData(code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', country: 'Zambia', flag: '🇿🇲'),
  CurrencyData(code: 'ZWL', symbol: '\$', name: 'Zimbabwean Dollar', country: 'Zimbabwe', flag: '🇿🇼'),
];
